// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DSR_KAZAR_N1.Migrations
{
    [DbContext(typeof(dbContext))]
    partial class dbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.4");

            modelBuilder.Entity("DSR_KAZAR_N1.Models.Racun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("cenaSkupaj")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("datumIzdaje")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Racun");
                });

            modelBuilder.Entity("DSR_KAZAR_N1.Models.Slika", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("cena")
                        .HasColumnType("REAL");

                    b.Property<string>("ime")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("jeUnikat")
                        .HasColumnType("INTEGER");

                    b.Property<int>("letoIzdaje")
                        .HasColumnType("INTEGER");

                    b.Property<int>("racunId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("racunId");

                    b.ToTable("Slika");
                });

            modelBuilder.Entity("UporabnikModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("TEXT");

                    b.Property<string>("address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("birthdate")
                        .HasColumnType("TEXT");

                    b.Property<string>("birthplace")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("country")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("emso")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("post")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("postnum")
                        .HasColumnType("INTEGER");

                    b.Property<string>("surname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Uporabnik");

                    b.HasDiscriminator<string>("Discriminator").HasValue("UporabnikModel");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("DSR_KAZAR_N1.Models.UporabnikZGesli", b =>
                {
                    b.HasBaseType("UporabnikModel");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("password2")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("UporabnikZGesli");
                });

            modelBuilder.Entity("DSR_KAZAR_N1.Models.Slika", b =>
                {
                    b.HasOne("DSR_KAZAR_N1.Models.Racun", "racun")
                        .WithMany()
                        .HasForeignKey("racunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("racun");
                });
#pragma warning restore 612, 618
        }
    }
}
